### PR TITLE
Changes for sokol-gfx bindings cleanup.

### PR DESCRIPTION
**Pull request by floooh**
**DO NOT MERGE** :)

Changes for the upcoming breaking sokol-gfx update.

TODO:

- [x] update and rebuild shaders
- [x] fix example code

@colinbellino don't worry about this PR until I fixed the above todos. I'll ping when I will need your help with testing :)

### CODE REVIEW

**Comment by floooh** [comment]
Ok, @colinbellino when you have a minute, could you check if the changes in here compile and run?

There's a couple of things that could go wrong:

- the code-generated shader.jai files might be broken because I messed something up in sokol-shdc
- the example code might be slightly broken because I missed some required changes

Even if everything works, please do not merge this PR, but let me take care of that later. I'll need to coordinate that with merging the sokol main repository and sokol-shdc.

Cheers!

**Comment by colinbellino** [comment]
It looks like there is an issue with the stage property in the shader (missing `;`).

I still haven't implemented all examples in Jai, but the ones i have seem to be working after the fix. Let me know if there is a specific example/test you want me to do related to these changes.

**Comment by floooh** [comment]
Dang, yeah I see the error. Let me fix that in sokol-shdc and update the PR.

**Comment by floooh** [comment]
Ok I fixed that problem in sokol-shdc and updated the code-generated shaders.

I basically only need to know if the examples are building and running, then I can mark this PR as 'done' and later merge into master as part of a coordinated 'big merge' that's probably still a couple of days out.

Thanks :)

**Comment by colinbellino** [comment]
Can confirm this builds and runs correctly with the fix 👍🏻

**Comment by floooh** [comment]
Thanks! Ok, then I'll keep this PR in draft mode until I'm ready to do the 'big merge'.

**Comment by floooh** [comment]
...doing the big merge now... best to wait with testing until the sokol main repo is merged too.

Let me know if I broke anything (should be the case after the last test)

**Comment by colinbellino** [comment]
@floooh Looks like everything is working correctly, thanks! 👍🏻

**Pull request merged**
